###1 create
POST http://localhost:4001/boards HTTP/1.1
content-type: application/json

{
    "name": "Learn Guitar"
}
###2 create
POST http://localhost:4001/boards HTTP/1.1
content-type: application/json

{
    "name": "abcde",
    "content": "Lorem Ipsum is Lorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum isLorem Ipsum is"
}
###3 create
POST http://localhost:4001/boards HTTP/1.1
content-type: application/json

{
    "_id": "6006f8e357638c51a36a59c3",
    "name": "Learn Laravel x",
    "key": "jwsadsads"
}
### read
GET http://localhost:4001/boards HTTP/1.1


### update
PUT http://localhost:4001/boards HTTP/1.1
content-type: application/json

{
    "_id": "60200f8bc04d9027842aa144",
    "name": "New Category"
}